name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macOS-latest ]

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.402
    - name: List Directory
      run: ls -R
    - name: Restore dependencies
      run: dotnet restore ./src/Vlingo.UUID.sln
    - name: Build
      run: dotnet build ./src/Vlingo.UUID.sln --no-restore
    - name: Test
      run: dotnet test ./src/Vlingo.UUID.Tests/Vlingo.UUID.Tests.csproj --no-build --verbosity normal
    - name: slack - GitHub Actions Slack integration
      uses: act10ns/slack@v1.2.2
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      with:
        status: ${{ job.status }}
        steps: ${{ toJson(steps) }}
      if: always()